In [146]:
import numpy as np

#Part 1

Que1

In [147]:
Arr=np.array([10,20,30,40,50])

In [148]:
Arr

array([10, 20, 30, 40, 50])

In [149]:
Arr.shape

(5,)

In [150]:
Arr.size

5

In [151]:
Arr.dtype

dtype('int64')

Que2.

In [152]:
Arr2=np.arange(0,12).reshape(3,4)

In [153]:
Arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Que3

In [154]:
Arr0=np.zeros(5)

In [155]:
Arr0

array([0., 0., 0., 0., 0.])

In [156]:
Arr3=np.ones(5)

In [157]:
Arr3

array([1., 1., 1., 1., 1.])

In [158]:
arr0=np.eye(3,3)

In [159]:
arr0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Que4

In [160]:
arr=np.arange(1,11,10)

In [161]:
arr

array([1])

Que5.

In [162]:
arr=np.linspace(0,1,10)

In [163]:
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#Part-2

Que1

In [164]:
arr=np.array([10,20,30,40,50])

In [165]:
arr1=np.array([5,10,15,20,25])

In [166]:
arr3=arr1*arr

In [167]:
arr3

array([  50,  200,  450,  800, 1250])

In [168]:
arr3=arr1+arr

In [169]:
arr3

array([15, 30, 45, 60, 75])

In [170]:
arr3=arr-arr1

In [171]:
arr3

array([ 5, 10, 15, 20, 25])

In [172]:
arr3=arr/arr1

In [173]:
arr3

array([2., 2., 2., 2., 2.])

Que2.

In [174]:
arr=np.array([1,2,3,4,5,6])

In [175]:
sqr =arr ** 2
sqr

array([ 1,  4,  9, 16, 25, 36])

In [176]:
cube=arr**3
cube

array([  1,   8,  27,  64, 125, 216])

Que3

In [177]:
arr=arr*1.15
arr

array([1.15, 2.3 , 3.45, 4.6 , 5.75, 6.9 ])

Que4

In [178]:
arr=np.array([1,2,3,4,5])

In [179]:
arr1=np.array([5,4,3,2,1])

In [180]:
np.maximum(arr,arr1)

array([5, 4, 3, 4, 5])

In [181]:
np.minimum(arr,arr1)

array([1, 2, 3, 2, 1])

#Part3

Que1

In [182]:
arr=np.arange(0,21)

In [183]:
F_F=arr[0:5]
F_F

array([0, 1, 2, 3, 4])

In [184]:
L_f=arr[16:21]
L_f

array([16, 17, 18, 19, 20])

In [185]:
Sl=arr[5:15]
Sl

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [186]:
xl=arr[0:21:2]
xl

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Que2


In [187]:
arr=np.arange(0,11)

In [188]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Que3

In [189]:
slice_of_arr=arr[0:5]
slice_of_arr

array([100, 100, 100, 100, 100])

In [190]:
arr.view()

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [191]:
arr1=arr.copy()
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Que4

In [192]:
arr_rev=arr[::-1]
arr_rev

array([ 10,   9,   8,   7,   6,   5, 100, 100, 100, 100, 100])

#Part4

Que1

In [193]:
ar=np.array(([10,20,30],[40,50,60],[70,80,90]))

In [194]:
ar[1:2]

array([[40, 50, 60]])

In [195]:
ar[:,2:]

array([[30],
       [60],
       [90]])

In [196]:
ar[1,1]

np.int64(50)

Que2

In [197]:
ar[:2,1:]

array([[20, 30],
       [50, 60]])

Que3

In [198]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [199]:
arr[:1,:]

array([[1, 2, 3, 4, 5]])

In [200]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [201]:
arr[2,2]

np.int64(13)

In [202]:
arr[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

#Part5

Que1

In [203]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Que2

In [204]:
arr=np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
arr.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Que3

In [206]:
ar=np.arange(0,12).reshape(3,4)
ar
ar.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Que4

In [207]:
ar=np.arange(0,27).reshape(3,3,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [208]:
ar.transpose()

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [209]:
ar.swapaxes(0,1)


array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

#

#Part 6

Que1.

In [210]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [211]:
ar1=np.arange(10,19).reshape(3,3)
ar1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [212]:
ar+ar1

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [213]:
ar*ar1

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

Que2

In [214]:
ar.dot(ar1)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

Que3

In [215]:
ar=np.array(([1,2,3,4,5],
            [9,8,7,6,4]))
ar

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 4]])

In [216]:
a=ar.transpose()
a

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6],
       [5, 4]])

In [217]:
ar.dot(a)

array([[ 55,  90],
       [ 90, 246]])

#Part 7

Que1

In [218]:
ar=np.array([1,4,9,16,25,49])
ar

array([ 1,  4,  9, 16, 25, 49])

In [219]:
np.sqrt(ar)

array([1., 2., 3., 4., 5., 7.])

Que2

In [220]:
np.exp(ar)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 1.90734657e+21])

Que3

In [221]:
ar=np.random.randint(1,50,10)
ar

array([18, 40, 46, 25, 42,  3, 39, 25, 25, 17])

In [222]:
np.sqrt(ar)

array([4.24264069, 6.32455532, 6.78232998, 5.        , 6.4807407 ,
       1.73205081, 6.244998  , 5.        , 5.        , 4.12310563])

In [223]:
np.exp(ar)

array([6.56599691e+07, 2.35385267e+17, 9.49611942e+19, 7.20048993e+10,
       1.73927494e+18, 2.00855369e+01, 8.65934004e+16, 7.20048993e+10,
       7.20048993e+10, 2.41549528e+07])

In [224]:
np.abs(ar)

array([18, 40, 46, 25, 42,  3, 39, 25, 25, 17])

Que4

In [225]:
ar=np.random.randint(1,50,9)
ar1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [226]:
ar1=np.random.randint(1,50,9)
ar1

array([14,  4, 10, 36, 22, 19, 10, 30, 30])

In [227]:
np.maximum(ar,ar1)

array([14, 46, 10, 46, 27, 19, 27, 37, 30])

#Part 8

Que1

In [228]:
marks=np.array([35,72,48,90,55,28])
marks

array([35, 72, 48, 90, 55, 28])

In [229]:
np.where(marks<40,0,0)

array([0, 0, 0, 0, 0, 0])

Que2

In [230]:
income=np.random.randint(10000,100000,10)
income

array([75143, 74584, 43770, 28005, 89068, 30438, 10538, 26624, 17407,
       19229])

In [231]:
np.where(income>=50000,'High','Low')

array(['High', 'High', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'Low',
       'Low'], dtype='<U4')

Que3

In [232]:
ar=np.random.randint(1,50,10)
ar

array([32, 20, 15, 13, 38, 22, 45, 17,  1, 42])

In [233]:
np.where(ar>30,100,ar)

array([100,  20,  15,  13, 100,  22, 100,  17,   1, 100])

#Part 9

Que1

In [234]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [235]:
ar.sum()

np.int64(36)

In [236]:
ar.mean()

np.float64(4.0)

In [237]:
ar.std()

np.float64(2.581988897471611)

In [238]:
ar.var()

np.float64(6.666666666666667)

Que2

In [239]:
ar.sum(axis=0)

array([ 9, 12, 15])

In [240]:
ar.sum(axis=1)

array([ 3, 12, 21])

Que3

In [241]:
ar=np.random.randint(1,100,10)
ar

array([50, 24, 30, 11, 83, 97, 27, 59, 69, 52])

In [242]:
ar.mean()

np.float64(50.2)

In [243]:
ar.std()

np.float64(26.209921785461322)

In [244]:
ar.min()

np.int64(11)

In [245]:
ar.max()

np.int64(97)

Que 4

In [246]:
ar=np.random.choice([True,False],size=5)
ar

array([ True,  True, False, False, False])

In [247]:
ar.any()

np.True_

In [248]:
ar.all()

np.False_

#Part 10

Que 1

In [249]:
ar=np.random.randint(1,100,10)
ar

array([90, 15, 68, 31, 50, 28,  8, 65, 30, 32])

In [250]:
ar.sort()
ar

array([ 8, 15, 28, 30, 31, 32, 50, 65, 68, 90])

Que2

In [251]:
ar=np.array([1,2,3,3,4,3,5,5])

In [252]:
np.unique(ar)

array([1, 2, 3, 4, 5])

Que 3

In [253]:
Student_marks=np.array([20,30,30,20,30,49,59,53,53,60,23])

In [254]:
np.unique(Student_marks)

array([20, 23, 30, 49, 53, 59, 60])

Que 4

In [255]:
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [256]:
np.in1d(ar,ar1)

/tmp/ipykernel_2922/3883758535.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(ar,ar1)


array([False, False, False, False,  True, False, False, False, False])

#Part 11

Que 1

In [257]:
marks=np.random.randint(1,100,size=(10,3))
marks

array([[66, 47, 71],
       [36, 71, 52],
       [76, 62, 46],
       [10, 29, 49],
       [19, 95, 33],
       [83, 22, 24],
       [31, 49, 41],
       [10, 80, 71],
       [52, 61,  7],
       [ 8, 28,  9]])

In [258]:
marks.sum(axis=1)

array([184, 159, 184,  88, 147, 129, 121, 161, 120,  45])

In [259]:
average=marks.mean(axis=1)

In [260]:
np.where(average>=50,'Good','Bad')

array(['Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad',
       'Bad'], dtype='<U4')

Que 2

In [261]:
ar=np.arange(1,17).reshape(4,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [262]:
ar.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [263]:
ar.sum(axis=0)

array([28, 32, 36, 40])

In [264]:
ar.sum(axis=1)

array([10, 26, 42, 58])

In [265]:
ar.mean()

np.float64(8.5)

In [266]:
np.max(ar)

np.int64(16)

In [267]:
np.min(ar)

np.int64(1)

In [268]:
Slice=ar[1:3,1:3]
Slice

array([[ 6,  7],
       [10, 11]])

In [269]:
ar=np.array((([1,2,3],[1,2,3],[1,2,3])))
ar

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Que 3

In [270]:
ar=np.random.randn(20)
ar

array([-1.09504225,  0.70743498, -1.82694048,  0.01017761,  0.08946378,
       -1.18057094, -0.81595628,  0.66836287,  0.57755023,  0.5796392 ,
        0.42870269, -0.48441782,  0.18453313, -0.17252252,  1.8255209 ,
        0.54563228,  0.95491683,  1.5584794 , -1.49757443,  0.82380674])

In [271]:
ar.mean()

np.float64(0.09405979646418072)

In [272]:
ar.std()

np.float64(0.9596577022843321)

In [273]:
np.min(ar)

np.float64(-1.8269404782275824)

In [274]:
np.max(ar)

np.float64(1.8255209022908185)

In [275]:
ar.sort()
ar

array([-1.82694048, -1.49757443, -1.18057094, -1.09504225, -0.81595628,
       -0.48441782, -0.17252252,  0.01017761,  0.08946378,  0.18453313,
        0.42870269,  0.54563228,  0.57755023,  0.5796392 ,  0.66836287,
        0.70743498,  0.82380674,  0.95491683,  1.5584794 ,  1.8255209 ])

In [276]:
np.where(ar<0,0,ar)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.01017761, 0.08946378, 0.18453313,
       0.42870269, 0.54563228, 0.57755023, 0.5796392 , 0.66836287,
       0.70743498, 0.82380674, 0.95491683, 1.5584794 , 1.8255209 ])

Que 4

In [277]:
ar=np.arange(1,10).reshape(3,3)

In [278]:
ar1=np.arange(10,19).reshape(3,3)

In [279]:
ar+ar1

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [280]:
ar*ar1

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [281]:
ar.dot(ar1)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [282]:
ar=ar.transpose()

In [283]:
np.maximum(ar, ar1)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [284]:
np.minimum(ar,ar1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Que 5

In [285]:
ar=np.arange(1,25).reshape(4,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [286]:
s=ar[[0,2],:][:,[1,3]]
s

array([[ 2,  4],
       [14, 16]])

In [287]:
x=s.transpose()
x

array([[ 2, 14],
       [ 4, 16]])

In [288]:
ar.sum(axis=0)

array([40, 44, 48, 52, 56, 60])

In [289]:
ar.sum(axis=1)

array([ 21,  57,  93, 129])

In [290]:
np.unique(ar)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])